package uit.herec.dao.entity;
// default package
// Generated Jan 31, 2020 4:45:21 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Allergy generated by hbm2java
 */
@Entity
@Table(name = "allergy", catalog = "herec_uit")
public class Allergy implements java.io.Serializable {

    private Integer id;
    private Diagnosis diagnosis;
    private String name;
    private String status;
    private String reaction;

    public Allergy() {
    }

    public Allergy(Diagnosis diagnosis, String name, String status, String reaction) {
        this.diagnosis = diagnosis;
        this.name = name;
        this.status = status;
        this.reaction = reaction;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_diagnosis")
    public Diagnosis getDiagnosis() {
        return this.diagnosis;
    }

    public void setDiagnosis(Diagnosis diagnosis) {
        this.diagnosis = diagnosis;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "status", length = 100)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "reaction", length = 100)
    public String getReaction() {
        return this.reaction;
    }

    public void setReaction(String reaction) {
        this.reaction = reaction;
    }

}
