package uit.herec.dao.entity;
// default package
// Generated Jan 31, 2020 4:45:21 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AppRole generated by hbm2java
 */
@Entity
@Table(name = "app_role", catalog = "herec_uit", uniqueConstraints = @UniqueConstraint(columnNames = "role"))
public class AppRole implements java.io.Serializable {

    private Integer id;
    private String role;
    private Set<AppUser> appUsers = new HashSet<AppUser>(0);

    public AppRole() {
    }

    public AppRole(String role) {
        this.role = role;
    }

    public AppRole(String role, Set<AppUser> appUsers) {
        this.role = role;
        this.appUsers = appUsers;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "role", unique = true, nullable = false, length = 100)
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "appRole")
    public Set<AppUser> getAppUsers() {
        return this.appUsers;
    }

    public void setAppUsers(Set<AppUser> appUsers) {
        this.appUsers = appUsers;
    }

}
