package uit.herec.dao.entity;
// default package
// Generated Jan 31, 2020 4:45:21 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Diagnosis generated by hbm2java
 */
@Entity
@Table(name = "diagnosis", catalog = "herec_uit")
public class Diagnosis implements java.io.Serializable {

    private Integer id;
    private AppUser appUser;
    private Organization organization;
    private String clinician;
    private Date createdAt;
    private String symtoms;
    private Set<Allergy> allergies = new HashSet<Allergy>(0);
    private Set<Medication> medications = new HashSet<Medication>(0);

    public Diagnosis() {
    }

    public Diagnosis(AppUser appUser, Organization organization, String clinician, Date createdAt, String symtoms,
            Set<Allergy> allergies, Set<Medication> medications) {
        this.appUser = appUser;
        this.organization = organization;
        this.clinician = clinician;
        this.createdAt = createdAt;
        this.symtoms = symtoms;
        this.allergies = allergies;
        this.medications = medications;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user")
    public AppUser getAppUser() {
        return this.appUser;
    }

    public void setAppUser(AppUser appUser) {
        this.appUser = appUser;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_org")
    public Organization getOrganization() {
        return this.organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    @Column(name = "clinician", length = 100)
    public String getClinician() {
        return this.clinician;
    }

    public void setClinician(String clinician) {
        this.clinician = clinician;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Column(name = "symtoms", length = 65535)
    public String getSymtoms() {
        return this.symtoms;
    }

    public void setSymtoms(String symtoms) {
        this.symtoms = symtoms;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosis")
    public Set<Allergy> getAllergies() {
        return this.allergies;
    }

    public void setAllergies(Set<Allergy> allergies) {
        this.allergies = allergies;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosis")
    public Set<Medication> getMedications() {
        return this.medications;
    }

    public void setMedications(Set<Medication> medications) {
        this.medications = medications;
    }

}
