---
    Organizations:

        - &OrdererOrg
            Name: OrdererOrg
            ID: OrdererMSP
            MSPDir: crypto-config/ordererOrganizations/herec.uit/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('OrdererMSP.member')"
                Writers:
                    Type: Signature
                    Rule: "OR('OrdererMSP.member')"
                Admins:
                    Type: Signature
                    Rule: "OR('OrdererMSP.admin')"
    
        - &Client
            Name: ClientMSP
            ID: ClientMSP
            MSPDir: crypto-config/peerOrganizations/client.herec.uit/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('ClientMSP.admin', 'ClientMSP.peer', 'ClientMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('ClientMSP.admin', 'ClientMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('ClientMSP.admin')"
            AnchorPeers:
                - Host: peer0.client.herec.uit
                  Port: 7051
    
        - &Quan12
            Name: Quan12MSP
            ID: Quan12MSP
            MSPDir: crypto-config/peerOrganizations/quan12.herec.uit/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('Quan12MSP.admin', 'Quan12MSP.peer', 'Quan12MSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('Quan12MSP.admin', 'Quan12MSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('Quan12MSP.admin')"
    
            AnchorPeers:
                - Host: peer0.quan12.herec.uit
                  Port: 9051

        - &TanPhu
            Name: TanPhuMSP
            ID: TanPhuMSP
            MSPDir: crypto-config/peerOrganizations/tanphu.herec.uit/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('TanPhuMSP.admin', 'TanPhuMSP.peer', 'TanPhuMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('TanPhuMSP.admin', 'TanPhuMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('TanPhuMSP.admin')"
    
            AnchorPeers:
                - Host: peer0.tanphu.herec.uit
                  Port: 11051

    Capabilities:
        Channel: &ChannelCapabilities
            V1_4_3: true
            V1_3: false
            V1_1: false
        Orderer: &OrdererCapabilities
            V1_4_2: true
            V1_1: false
        Application: &ApplicationCapabilities
            V1_4_2: true
            V1_3: false
            V1_2: false
            V1_1: false
    
    Application: &ApplicationDefaults
        Organizations:
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
        Capabilities:
            <<: *ApplicationCapabilities

    Orderer: &OrdererDefaults
        OrdererType: solo
        Addresses:
            - orderer.herec.uit:7050
        BatchTimeout: 2s
        BatchSize:
            MaxMessageCount: 10
            AbsoluteMaxBytes: 99 MB
            PreferredMaxBytes: 512 KB
        Kafka:
            Brokers:
                - 127.0.0.1:9092
        EtcdRaft:
            Consenters:
                - Host: orderer.herec.uit
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer.herec.uit/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer.herec.uit/tls/server.crt
                - Host: orderer2.herec.uit
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer2.herec.uit/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer2.herec.uit/tls/server.crt
                - Host: orderer3.herec.uit
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer3.herec.uit/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer3.herec.uit/tls/server.crt
                - Host: orderer4.herec.uit
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer4.herec.uit/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer4.herec.uit/tls/server.crt
                - Host: orderer5.herec.uit
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer5.herec.uit/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer5.herec.uit/tls/server.crt
        Organizations:
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
            BlockValidation:
                Type: ImplicitMeta
                Rule: "ANY Writers"

    Channel: &ChannelDefaults
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
        Capabilities:
            <<: *ChannelCapabilities
    
    Profiles:
        TwoOrgsOrdererGenesis:
            <<: *ChannelDefaults
            Orderer:
                <<: *OrdererDefaults
                Organizations:
                    - *OrdererOrg
                Capabilities:
                    <<: *OrdererCapabilities
            Consortiums:
                SampleConsortium:
                    Organizations:
                        - *Client
                        - *Quan12
                        - *TanPhu
        TwoOrgsChannel:
            Consortium: SampleConsortium
            <<: *ChannelDefaults
            Application:
                <<: *ApplicationDefaults
                Organizations:
                    - *Client
                    - *Quan12
                    - *TanPhu
                Capabilities:
                    <<: *ApplicationCapabilities
    
        SampleDevModeKafka:
            <<: *ChannelDefaults
            Capabilities:
                <<: *ChannelCapabilities
            Orderer:
                <<: *OrdererDefaults
                OrdererType: kafka
                Kafka:
                    Brokers:
                    - kafka.herec.uit:9092
    
                Organizations:
                - *OrdererOrg
                Capabilities:
                    <<: *OrdererCapabilities
            Application:
                <<: *ApplicationDefaults
                Organizations:
                - <<: *OrdererOrg
            Consortiums:
                SampleConsortium:
                    Organizations:
                    - *Client
                    - *Quan12
                    - *TanPhu
    
        SampleMultiNodeEtcdRaft:
            <<: *ChannelDefaults
            Capabilities:
                <<: *ChannelCapabilities
            Orderer:
                <<: *OrdererDefaults
                OrdererType: etcdraft
                EtcdRaft:
                    Consenters:
                    - Host: orderer.herec.uit
                      Port: 7050
                      ClientTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer.herec.uit/tls/server.crt
                      ServerTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer.herec.uit/tls/server.crt
                    - Host: orderer2.herec.uit
                      Port: 7050
                      ClientTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer2.herec.uit/tls/server.crt
                      ServerTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer2.herec.uit/tls/server.crt
                    - Host: orderer3.herec.uit
                      Port: 7050
                      ClientTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer3.herec.uit/tls/server.crt
                      ServerTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer3.herec.uit/tls/server.crt
                    - Host: orderer4.herec.uit
                      Port: 7050
                      ClientTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer4.herec.uit/tls/server.crt
                      ServerTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer4.herec.uit/tls/server.crt
                    - Host: orderer5.herec.uit
                      Port: 7050
                      ClientTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer5.herec.uit/tls/server.crt
                      ServerTLSCert: crypto-config/ordererOrganizations/herec.uit/orderers/orderer5.herec.uit/tls/server.crt
                Addresses:
                    - orderer.herec.usedit:7050
                    - orderer2.herec.uit:7050
                    - orderer3.herec.uit:7050
                    - orderer4.herec.uit:7050
                    - orderer5.herec.uit:7050
    
                Organizations:
                - *OrdererOrg
                Capabilities:
                    <<: *OrdererCapabilities
            Application:
                <<: *ApplicationDefaults
                Organizations:
                - <<: *OrdererOrg
            Consortiums:
                SampleConsortium:
                    Organizations:
                    - *Client
                    - *Quan12
                    - *TanPhu
    