OrdererOrgs:
  - Name: Orderer
    Domain: herec.uit
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

PeerOrgs:
  - Name: Client
    Domain: client.herec.uit
    EnableNodeOUs: true

    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Quan12
    Domain: quan12.herec.uit
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: TanPhu
    Domain: tanphu.herec.uit
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
